// mapPlatforms.js
export const PLATFORM_MAP = [
  // ✅ กลุ่มพิเศษ
  {
    key: 'premium',
    name: 'บัญชีพรีเมียม | คีย์',
    match: [
      'canva pro',
      'chatgpt business',
      'youtube premium',
      'license key',
      'ดาวน์โหลด ไฟล์ลิขสิทธิ์',
      'shutterstock',
      'envato',
      'adobestock',
      'istockphoto',
      'motion array',
    ],
  },
  {
    key: 'thailand',
    name: 'ประเทศไทย',
    match: [
      '🇹🇭',                        // มีธงไทย
      ' ประเทศไทย',                 // คำว่าประเทศไทย
      ' บัญชีไทย',                 // บัญชีไทย
      'thailand services',
      'tiktok 🎯 thailand',
      'youtube ► thailand',
      'รวมบริการยูทูป ประเทศไทย',
      'instagram ► รวมบริการไอจี ประเทศไทย',
      'facebook ► รวมบริการไทย',
      'facebook ► ถูกใจเพจ | ผู้ติดตาม [ เพจ/โปรไฟล์ ] 💎 [ บัญชีไทย ]',
      'facebook ► ไลค์โพส reactions',
      'facebook ► แชร์โพส 🔗 บัญชีไทย',
      'facebook ► คอมเม้นท์ 💬 บัญชีไทย',
      'facebook 📝 รีวิวแฟนเพจ,แนะนำเพจ บัญชีไทย',
      'x.com | twitter services ► รวมบริการประเทศไทย',
      'shopee / lazada services ► บัญชีไทย',
      'ส่วนเสริม ไลฟ์สด shopee.co.th',
      'spotify ► thailand',
    ],
  },

  // ✅ Traffic แยกออกมาต่างหาก และอยู่ก่อน SEO
  {
    key: 'traffic',
    name: 'เพิ่มคนเข้าเว็บ',
    match: [
      // ทราฟฟิก / เข้าเว็บ
      'เพิ่มทราฟฟิคเข้าเว็บไซต์',
      'website traffic',
      'mobile traffic',
      'premium traffic',
      'pop-under traffic',
      'worldwide',
      'exchange platforms (ptc)',
      'แหล่งอ้างอิง เลือกประเทศ',
      'choose geo',
      'website 💎 premium traffic packages',
      'website traffic 🇹🇭 ประเทศไทย',

      // รวมฝั่ง SEO มาด้วย
      'backlinks & website seo',
      'seo package ranking',
      'social signals',
      'best google ranking',
      'search console',
      ' seo',
    ],
  },

  // แพลตฟอร์มหลัก
  { key: 'tiktok',    name: 'TikTok',          match: ['tiktok'] },
  { key: 'facebook',  name: 'Facebook',       match: ['facebook'] },
  { key: 'instagram', name: 'Instagram',      match: ['instagram'] },
  { key: 'youtube',   name: 'YouTube',        match: ['youtube', 'yt '] },
  { key: 'threads',   name: 'Threads',        match: ['threads'] },
  { key: 'twitter',   name: 'X (Twitter)',    match: ['x (twitter)', ' twitter', ' tw '] },
  { key: 'line',      name: 'Line Official',  match: ['Line Official Account ', 'Line OpenChat', 'Line Voom '] },
  { key: 'telegram',  name: 'Telegram',       match: ['telegram'] },
  { key: 'discord',   name: 'Discord',        match: ['discord'] },
  { key: 'twitch',    name: 'Twitch',         match: ['twitch'] },
  { key: 'spotify',   name: 'Spotify',        match: ['spotify'] },
  { key: 'kick',      name: 'Kick',           match: [' kick '] },

  { key: 'shopee', name: 'ไลฟ์สด Shopee', match: ['shopee', 'shp '] },

  // fallback
  { key: 'other',  
    name: 'อื่นๆ', 
    match: [
      '🆓【﻿𝗙𝗿𝗲𝗲 𝗧𝗿𝗶𝗮𝗹】บริการทดลองฟรี ⏱ วันละ 1 ครั้ง',
      '💝 โปรโมชั่นประจำปี 2025 — บริการส่งเสริมการขาย ✖️ ไม่มีรับประกัน ⛔️ ไม่มียกเลิก',
      '➖➖➖➖➖➖➖➖➖🔻 บริการมาใหม่ 🔻➖➖➖➖➖➖➖➖➖',
      '✅Canva Pro 🖌️ ปล็ดล๊อกทุกฟังก์ชั่น ถูกที่สุด',
      '✅ChatGPT Business ✨ Google AI Ultra VEO3',
      '✅Disney+ 🔴 Amazon Prime 🔴 Youtube Premium',
      '✅License Key 🔑  Microsoft Office, Windows Key ✈️ บริการพิเศษจากเรา 📧 ใส่อีเมล์เพื่อสั่งซื้อ',
      '✅License Key 🔑 Adobe, AutoDesk, Steam, Kaspersky, Grammarly, Duolingo, อื่นๆ 📧 ใส่อีเมล์เพื่อสั่งซื้อ',
      '✅ดาวน์โหลด ไฟล์ลิขสิทธิ์ 📷 ShutterStock, Freepik, Flaticon, Envato, SketchUp, AdobeStock, iStockPhoto, Motion Array',
      '✅🇹🇭 Meta.ai Ⓜ️ เมต้า บัญชีไทย - ไลค์ / ผู้ติดตาม',
      '✅🇹🇭 Zepeto 🦹 เซเปโต้ บัญชีไทย',
      '✅🇹🇭 Lemon8 🍋 เลมอน8 บัญชีไทย - ไลค์ / ผู้ติดตาม / เซฟ',
      '✅🇹🇭 CapCut 📽️ แคปคัท บัญชีไทย - ไลค์วิดีโอ / ผู้ติดตาม',
      '✅🇹🇭 Joylada 📖 จอยลดา บัญชีไทย - ไลค์ / ผู้ติดตาม / อ่าน',
      '✅BiliBili 📺 ไลค์ / ผู้ติดตาม / วิววิดีโอ',
      '➖➖➖➖➖➖➖➖➖🔻 𝐓𝐢𝐤𝐓𝐨𝐤 🔻➖➖➖➖➖➖➖➖➖',
      '✅TikTok 🎯 Thailand 🇹🇭 Services – รวมบริการประเทศไทย 🚫 ไม่มีรับประกัน',
      '✅TikTok 🎯 All Services – รวมบริการทางเลือก 🪅 𝐒𝐯.𝐢𝐒𝐞𝐞',
      '✅TikTok 👁️ Video Views – วิววิดีโอ',
      'TikTok 👤 Followers – ผู้ติดตา',
      '⚠️ คำสั่งซื้อหนาแน่น ✅TikTok ❤️️ Likes – ไลค์ • จัดส่งเงียบ ซ่อนโปรไฟล์ 🫣 ทำงานไว',
      'TikTok ❤️️ Likes',
      'TikTok 💾 Saves',
      'TikTok 🔗 Shares',
      'TikTok 👀 Story Services',
      'TikTok 💬 Comments',
      'TikTok ❤️️ Comment Likes',
      'TikTok 🔴 Live Stream',
      'TikTok 💬 Live Comments',
      'TikTok ❤️️ Live Likes',
      '✅TikTok 🥊 PK Battle Points',
      '✅TikTok 💔 Not Interested',
      '✅Douyin',
      '➖➖➖➖➖🔻𝐘𝐨𝐮𝐭𝐮𝐛𝐞🔻➖➖➖➖➖',
      'YouTube Views',
      'YouTube รวมบริการ',
      'YouTube 🔎 CTR Search Views',
      '✅🇹🇭 Youtube',
      '✅Youtube ► เพิ่มชั่วโมงช่อง',
      '✅Youtube Adword Views [Google Ads - Display Ads] 🤑 การดูจากโฆษณาผ่าน Display Ads',
      '✅YouTube ► Shorts Services',
      '✅YouTube Shorts Views',
      'YouTube 👍 Likes',
      'YouTube 👎 Dislikes',
      '✅Youtube 👍💬 ถูกใจ คอมเม้นท์',
      'Youtube Subscribers',
      '✅YouTube ► แชร์ไปโซเชียลมีเดีย',
      'Youtube 🔴 Live Stream',
      'Youtube 🔴 Like For Live Stream',
      'Youtube 🔴 Reaction For Live Stream',
      'Youtube 🔴 Live Chat Comments',
      '🪚 YouTube Split',
      '➖➖➖➖➖➖➖➖➖🔻 𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦 / 𝐓𝐡𝐫𝐞𝐚𝐝𝐬 🔻➖➖➖➖➖➖➖➖➖',
      '✅Threads',
      'Instagram',
      '🪚 Instagram Split',
      '➖➖➖➖➖➖➖➖➖🔻 รวมบริการ 𝐅𝐚𝐜𝐞𝐛𝐨𝐨𝐤 🔻➖➖➖➖➖➖➖➖➖',
      '✅🇹🇭 Facebook',
      '🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻',
      '✅Facebook Services',
      '🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻',
      '✅Facebook ► ผู้ติดตามแฟนเพจ',
      '✅Facebook ► ถูกใจแฟนเพจ',
      '🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻',
      '✅Facebook ► ไลค์โพส',
      '✅🅰️Facebook ► ออโต้ไลค์โพส',
      '🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻',
      '✅Facebook ► วิววิดีโอ',
      '✅Facebook 60K Minutes',
      '✅Facebook 120K Minutes',
      '✅Facebook 180K Minutes',
      '✅Facebook 600K Minutes',
      '✅Facebook ► ดูสตอรี่',
      '✅Facebook ► กดอิโมจิสตอรี่',
      '✅Facebook ► ซ่อนคอมเม้นท์ ในโพสต์',
      '✅Facebook ► คอมเม้นท์ / สุ่มอิโมจิ',
      '✅Facebook ► Saves บันทึกโพสต์',
      '✅Facebook ► Shares แชร์',
      '✅Facebook ► แชร์โพส แชร์รูป พิมพ์ข้อความที่อยากแชร์',
      '✅Facebook ► ไลค์คอมเม้นท์',
      '✅Facebook ► ตอบกลับคอมเม้นท์',
      '✅Facebook ► เพิ่มเพื่อนบัญชีเฟสบุ๊คส่วนตัว',
      '✅Facebook ► เพิ่มคนเข้ากลุ่ม | รีวิวเพจ | อีเว้นท์ | โพลโหวต',
      '✅Facebook 🔴 Live Stream',
      '✅🅰️Facebook 🔴 Auto Live Stream',
      '🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻',
      'Facebook Brazil',
      'Facebook Pakistan',
      ' Facebook Split',
      '➖➖➖➖➖➖➖➖➖🔻 𝐗.𝐜𝐨𝐦 | 𝐓𝐰𝐢𝐭𝐭𝐞𝐫 🔻➖➖➖➖➖➖➖➖➖',
      'X.com | Twitter',
      '➖➖➖➖➖➖➖➖➖🔻 𝐒𝐡𝐨𝐩𝐞𝐞 🔻➖➖➖➖➖➖➖➖➖',
      'Shopee',
      '✅🇹🇭 ส่วนเสริม ไลฟ์สด Shopee.co.th',
      '➖➖➖➖➖➖➖➖➖🔻 𝐋𝐢𝐧𝐞 𝐎𝐟𝐟𝐢𝐜𝐢𝐚𝐥 🔻➖➖➖➖➖➖➖➖➖',
      'Line',
      '➖➖➖➖➖➖➖➖➖🔻 𝐃𝐢𝐬𝐜𝐨𝐫𝐝 🔻➖➖➖➖➖➖➖➖➖',
      'Discord',
      '➖➖➖➖➖➖➖➖➖🔻 𝐓𝐞𝐥𝐞𝐠𝐫𝐚𝐦 🔻➖➖➖➖➖➖➖➖➖',
      'Telegram',
      '➖➖➖➖➖➖➖➖➖🔻 𝐒𝐩𝐨𝐭𝐢𝐟𝐲 🔻➖➖➖➖➖➖➖➖➖',
      'Spotify',
      '➖➖➖➖➖➖➖➖➖🔻 𝐓𝐰𝐢𝐭𝐜𝐡 🔻➖➖➖➖➖➖➖➖➖',
      'Twitch',
      '➖➖➖➖➖➖➖➖➖🔻 𝐊𝐢𝐜𝐤.𝐜𝐨𝐦 🔻➖➖➖➖➖➖➖➖➖',
      'Kick.com',
      '➖➖➖➖➖➖➖➖➖🔻 𝐖𝐡𝐚𝐭𝐬𝐚𝐩𝐩 🔻➖➖➖➖➖➖➖➖➖',
      'Whatsapp',
      '➖➖➖➖➖➖➖➖➖🔻 อื่นๆ 🔻➖➖➖➖➖➖➖➖➖',
      'SoundCloud',
      'Kwai',
      'LinkedIn',
      'Dailymotion',
      '✅Likee',
      '✅Pinterest',
      '✅Tumblr',
      '✅Trovo',
      '✅BlueSky',
      '✅Vimeo',
      '✅Sooplive',
      '✅Naver TV Views',
      '✅Naver Chzzk',
      '✅Audiomack',
      '✅Reddit',
      '✅Deezer',
      '✅Potato',
      'Quora.Com',
      '✅Napster',
      'Rumble',
      '✅Rutube',
      '✅DLive',
      'BIGO.TV Live Stream Views',
      '✅Bigo Live',
      '✅SnapChat',
      'GitHub',
      '✅Binance',
      '✅IMDB',
      '✅Mobile App Installs ► iOS / Android',
      '✅Apple Music',
      '✅Google Map',
      '✅Dexscreener กดอิโมจิ 🔥🚀🚩💩',
      '✅CoinMarketCap',
      '✅PUBG Mobile UC (Global)',
      '✅Free Fire',
      '✅Steam Points',
      '✅ส่งรายงาน ❌ Spam Report Services',
      '➖➖➖➖➖➖➖➖➖🔻 𝐖𝐞𝐛𝐬𝐢𝐭𝐞 𝐓𝐫𝐚𝐟𝐟𝐢𝐜 + 𝐒𝐄𝐎 🔻➖➖➖➖➖➖➖➖➖',
      '✅Mobile Traffic',
      '🌐เพิ่มทราฟฟิคเข้าเว็บไซต์',
      '🌐Google Search Console',
      '🚀Website',
      '🔗Backlinks',
      '📊Social Signals',
      '✅📊SEO Package Ranking',
      '✅🔴Premium Pop-Under Traffic',
      'new for test_wow',
      'Opensea.com',
      'Coingecko.com',
      'Superrare.com',
      'Crypto.com',
      'Rarible.com',
      'Youtube | Short Views - Adword [Google Ads]'
    ] 
  },
];
